In [1]:
import pandas as pd
import matplotlib
#matplotlib.use('Agg')
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
import json

with open('krx_total_list.txt','r') as f:
    tickers = json.loads(f.read())
len(tickers)

2085

# Data extraction for chart.js

In [3]:
test = pd.read_pickle('./data10y_close_pickle_2/008500')
test.shape

(2699, 1)

In [4]:
test.index.tolist()[:10]

[Timestamp('2008-01-02 00:00:00'),
 Timestamp('2008-01-03 00:00:00'),
 Timestamp('2008-01-04 00:00:00'),
 Timestamp('2008-01-07 00:00:00'),
 Timestamp('2008-01-08 00:00:00'),
 Timestamp('2008-01-09 00:00:00'),
 Timestamp('2008-01-10 00:00:00'),
 Timestamp('2008-01-11 00:00:00'),
 Timestamp('2008-01-14 00:00:00'),
 Timestamp('2008-01-15 00:00:00')]

In [13]:
test.index.tolist()[-10:]

[Timestamp('2018-11-21 00:00:00'),
 Timestamp('2018-11-22 00:00:00'),
 Timestamp('2018-11-23 00:00:00'),
 Timestamp('2018-11-26 00:00:00'),
 Timestamp('2018-11-27 00:00:00'),
 Timestamp('2018-11-28 00:00:00'),
 Timestamp('2018-11-29 00:00:00'),
 Timestamp('2018-11-30 00:00:00'),
 Timestamp('2018-12-03 00:00:00'),
 Timestamp('2018-12-04 00:00:00')]

In [12]:
test.index.tolist()[-1:]

[Timestamp('2018-12-04 00:00:00')]

In [134]:
test.index.year >= 2016

array([False, False, False, ...,  True,  True,  True])

In [135]:
test[test.index.year >= 2016].head()

Close
Date               
2016-01-04  29200.0
2016-01-05  29350.0
2016-01-06  28250.0
2016-01-07  28300.0
2016-01-08  28750.0

In [139]:
test[test.index.year >= 2016].shape

(714, 1)

In [138]:
test[test.index.year == 2016].shape

(246, 1)

In [110]:
pd.datetime(2018,12,21)

datetime.datetime(2018, 12, 21, 0, 0)

In [142]:
test.index.year[2010:2012]

Int64Index([2016, 2016], dtype='int64', name='Date')

In [141]:
test.index[2010:2012]

DatetimeIndex(['2016-02-11', '2016-02-12'], dtype='datetime64[ns]', name='Date', freq=None)

In [21]:
test.index.tolist()[0] < test.index.tolist()[1]

True

In [145]:
test.index.tolist()[0] < targetDate

array([ True])

In [144]:
test.index[0] > test.index[1]

False

In [11]:
test.index[0] > targetDate

array([False])

In [30]:
test[test.index>pd.datetime(2018,1,6)].head()

Close
Date               
2018-01-08  23400.0
2018-01-09  23400.0
2018-01-10  23450.0
2018-01-11  23500.0
2018-01-12  23250.0

In [41]:
test[test.index>pd.datetime(2018,1,6)].head()

Close
Date               
2018-01-08  23400.0
2018-01-09  23400.0
2018-01-10  23450.0
2018-01-11  23500.0
2018-01-12  23250.0

In [45]:
test[test.index <= pd.datetime(2018,1,6)].head()

Close
Date               
2008-01-02  20400.0
2008-01-03  20300.0
2008-01-04  19900.0
2008-01-07  20000.0
2008-01-08  19900.0

In [46]:
test.loc[pd.datetime(2018,1,1):pd.datetime(2018,1,6)]

Close
Date               
2018-01-02  24350.0
2018-01-03  24450.0
2018-01-04  24450.0
2018-01-05  24350.0

In [19]:
targetDate

DatetimeIndex(['2018-09-05'], dtype='datetime64[ns]', freq=None)

In [18]:
targetDate.strftime('%Y-%m-%d')

Index(['2018-09-05'], dtype='object')

In [16]:
test.loc['2014-01-01':targetDate.strftime('%Y-%m-%d')]

TypeError: Cannot convert input [Index(['2018-09-05'], dtype='object')] of type <class 'pandas.core.indexes.base.Index'> to Timestamp

In [47]:
pd.datetime(2018,1,6)-pd.DateOffset(90)

Timestamp('2017-10-08 00:00:00')

In [7]:
targetDate = pd.DatetimeIndex(test.index.tolist()[-1:])-pd.DateOffset(90)
targetDate

DatetimeIndex(['2018-09-05'], dtype='datetime64[ns]', freq=None)

In [24]:
test.index.strftime('%Y-%m-%d').tolist()

['2008-01-02',
 '2008-01-03',
 '2008-01-04',
 '2008-01-07',
 '2008-01-08',
 '2008-01-09',
 '2008-01-10',
 '2008-01-11',
 '2008-01-14',
 '2008-01-15',
 '2008-01-16',
 '2008-01-17',
 '2008-01-18',
 '2008-01-21',
 '2008-01-22',
 '2008-01-23',
 '2008-01-24',
 '2008-01-25',
 '2008-01-28',
 '2008-01-29',
 '2008-01-30',
 '2008-01-31',
 '2008-02-01',
 '2008-02-04',
 '2008-02-05',
 '2008-02-11',
 '2008-02-12',
 '2008-02-13',
 '2008-02-14',
 '2008-02-15',
 '2008-02-18',
 '2008-02-19',
 '2008-02-20',
 '2008-02-21',
 '2008-02-22',
 '2008-02-25',
 '2008-02-26',
 '2008-02-27',
 '2008-02-28',
 '2008-02-29',
 '2008-03-03',
 '2008-03-04',
 '2008-03-05',
 '2008-03-06',
 '2008-03-07',
 '2008-03-10',
 '2008-03-11',
 '2008-03-12',
 '2008-03-13',
 '2008-03-14',
 '2008-03-17',
 '2008-03-18',
 '2008-03-19',
 '2008-03-20',
 '2008-03-21',
 '2008-03-24',
 '2008-03-25',
 '2008-03-26',
 '2008-03-27',
 '2008-03-28',
 '2008-03-31',
 '2008-04-01',
 '2008-04-02',
 '2008-04-03',
 '2008-04-04',
 '2008-04-07',
 '2008-04-

In [120]:
test[test.index < targetDate]

ValueError: Lengths must match to compare

In [123]:
test.index

DatetimeIndex(['2008-01-02', '2008-01-03', '2008-01-04', '2008-01-07',
               '2008-01-08', '2008-01-09', '2008-01-10', '2008-01-11',
               '2008-01-14', '2008-01-15',
               ...
               '2018-11-21', '2018-11-22', '2018-11-23', '2018-11-26',
               '2018-11-27', '2018-11-28', '2018-11-29', '2018-11-30',
               '2018-12-03', '2018-12-04'],
              dtype='datetime64[ns]', name='Date', length=2699, freq=None)

In [126]:
test.index < targetDate

ValueError: Lengths must match to compare

In [133]:
test.datetime(test['Date'], format='%Y-%m-%d')

AttributeError: 'DataFrame' object has no attribute 'datetime'

In [132]:
test.index.tolist()[test.index.Date < targetDate]

AttributeError: 'DatetimeIndex' object has no attribute 'Date'

In [28]:
test.set_index('Date')['2019':'2019']

KeyError: 'Date'

In [131]:
test.index['2019']

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [6]:
test.index.strftime('%Y-%m-%d').tolist()[:10]

['2008-01-02',
 '2008-01-03',
 '2008-01-04',
 '2008-01-07',
 '2008-01-08',
 '2008-01-09',
 '2008-01-10',
 '2008-01-11',
 '2008-01-14',
 '2008-01-15']

In [16]:
test.index.strftime('%Y-%m-%d').tolist()[-1:]

['2018-12-04']

In [7]:
test.reset_index().Date.dt.strftime('%Y-%m-%d').tolist()[:10]

['2008-01-02',
 '2008-01-03',
 '2008-01-04',
 '2008-01-07',
 '2008-01-08',
 '2008-01-09',
 '2008-01-10',
 '2008-01-11',
 '2008-01-14',
 '2008-01-15']

In [9]:
test.reset_index().dtypes

Date     datetime64[ns]
Close           float64
dtype: object

In [10]:
pd.to_datetime(test.index)

DatetimeIndex(['2008-01-02', '2008-01-03', '2008-01-04', '2008-01-07',
               '2008-01-08', '2008-01-09', '2008-01-10', '2008-01-11',
               '2008-01-14', '2008-01-15',
               ...
               '2018-11-21', '2018-11-22', '2018-11-23', '2018-11-26',
               '2018-11-27', '2018-11-28', '2018-11-29', '2018-11-30',
               '2018-12-03', '2018-12-04'],
              dtype='datetime64[ns]', name='Date', length=2699, freq=None)

In [11]:
pd.to_datetime(test.index).tolist()[:10]

[Timestamp('2008-01-02 00:00:00'),
 Timestamp('2008-01-03 00:00:00'),
 Timestamp('2008-01-04 00:00:00'),
 Timestamp('2008-01-07 00:00:00'),
 Timestamp('2008-01-08 00:00:00'),
 Timestamp('2008-01-09 00:00:00'),
 Timestamp('2008-01-10 00:00:00'),
 Timestamp('2008-01-11 00:00:00'),
 Timestamp('2008-01-14 00:00:00'),
 Timestamp('2008-01-15 00:00:00')]

### pd -> CSV file

In [12]:
test.to_csv('test-csv.csv', header=False)

In [13]:
test_new = test[['Close']].copy()

In [17]:
len(test_new)

1453

### pd -> csv , select column

In [123]:
# header = ['Close']
test.to_csv('test-csv-close.csv', header=False, columns = ['Close'])

### CSV

In [25]:
# 10 year 'Close' , to csv

def data_extract(n1, n2):
    cnt = 0;log=[]
    print('request data from {} to {}, processing..'.format(n1,n2),end='')
    for i,v in tickers.items():
        cnt+=1
        if cnt > n1 and '마켓' in v:
            ticker = i+'.'+v['마켓']
            try:
                df = pd.read_pickle('./data10y/{}'.format(ticker))
                df.to_csv('./data10y_close_csv/{}.csv'.format(ticker), header=False, columns = ['Close'])
                log.append((cnt,ticker,'plotted.',v['회사명']))
                print('.',end='')
            except Exception as e:
                log.append((cnt,ticker,'failed.',e,v['회사명']))
                print(cnt,ticker,'failed',e,v['회사명'])
                pass
        if cnt == n2 :
            break
    print(' extraction finished.')
    filename = 'log-extract-{}-{}.txt'.format(n1,n2)
    with open('./data10y_close_csv/'+filename, 'w') as f:
        for i in log:
            f.write("{}\n".format(i))
        print(filename,'file saved!')
data_extract(1000,2085)

request data from 1000 to 2085, processing..............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................

### Pickle

In [22]:
# 10 year 'Close' , to pickle

def data_extract(n1, n2):
    cnt = 0;log=[]
    print('request data from {} to {}, processing..'.format(n1,n2),end='')
    for i,v in tickers.items():
        cnt+=1
        if cnt > n1 and '마켓' in v:
            ticker = i+'.'+v['마켓']
            try:
                df = pd.read_pickle('./data10y/{}'.format(ticker))
                df_new = df[['Close']].copy()
                df_new.to_pickle('./data10y_close_pickle/{}'.format(ticker))
                log.append((cnt,ticker,'extracted.',v['회사명']))
                print('.',end='')
            except Exception as e:
                log.append((cnt,ticker,'failed.',e,v['회사명']))
                print(cnt,ticker,'failed',e,v['회사명'])
                pass
        if cnt == n2 :
            break
    print(' extraction finished.')
    filename = 'log-extract-{}-{}.txt'.format(n1,n2)
    with open('./data10y_close_pickle/'+filename, 'w') as f:
        for i in log:
            f.write("{}\n".format(i))
        print(filename,'file saved!')
data_extract(0,1000)

request data from 0 to 1000, processing...................................34 267270.KS failed [Errno 2] No such file or directory: './data10y/267270.KS' 현대건설기계
.........................................................................................................................................................................204 099340.KS failed [Errno 2] No such file or directory: './data10y/099340.KS' 하나니켈1호
205 099350.KS failed [Errno 2] No such file or directory: './data10y/099350.KS' 하나니켈2호
..............220 096300.KS failed [Errno 2] No such file or directory: './data10y/096300.KS' 베트남개발1
............................................................................................................................................................................................................................................................................................................................................................................................................

### Pickle-2

In [3]:
# 10 year 'Close' , to pickle

def data_extract(n1, n2):
    cnt = 0;log=[]
    print('request data from {} to {}, processing..'.format(n1,n2),end='')
    for i,v in tickers.items():
        cnt+=1
        if cnt > n1 and '마켓' in v:
            ticker = i+'.'+v['마켓']
            try:
                df = pd.read_pickle('./data10y/{}'.format(ticker))
                df_new = df[['Close']].copy()
                df_new.to_pickle('./data10y_close_pickle_2/{}'.format(i))
                log.append((cnt,ticker,'extracted.',v['회사명']))
                print('.',end='')
            except Exception as e:
                log.append((cnt,ticker,'failed.',e,v['회사명']))
                print(cnt,ticker,'failed',e,v['회사명'])
                pass
        if cnt == n2 :
            break
    print(' extraction finished.')
    filename = 'log-extract-{}-{}.txt'.format(n1,n2)
    with open('./data10y_close_pickle_2/'+filename, 'w') as f:
        for i in log:
            f.write("{}\n".format(i))
        print(filename,'file saved!')
data_extract(0,2085)

request data from 0 to 2085, processing...................................34 267270.KS failed [Errno 2] No such file or directory: './data10y/267270.KS' 현대건설기계
.........................................................................................................................................................................204 099340.KS failed [Errno 2] No such file or directory: './data10y/099340.KS' 하나니켈1호
205 099350.KS failed [Errno 2] No such file or directory: './data10y/099350.KS' 하나니켈2호
..............220 096300.KS failed [Errno 2] No such file or directory: './data10y/096300.KS' 베트남개발1
............................................................................................................................................................................................................................................................................................................................................................................................................